### ISSUE TITLE
Duration type

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#1]
https://github.com/Enfilde/CallsAndContacts/blob/e61aa5857dc2ed3fa886c0647c19178a51039886/src/main/Main/Call.java#L6
Use duration type instead of Data.

**Comment by Enfilde** [comment]
Fixed!   https://github.com/Enfilde/CallsAndContacts/blob/86b522d28971434ae854489dc8f21fed9afab848/src/main/Main/Call.java#L6
