### ISSUE TITLE
Extra variable use

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#12]
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L142-L146
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L159-L163
Full name can be returned after first equality without any variable.

**Comment by Enfilde** [comment]
Can not be so
