### ISSUE TITLE
The result of the constructor does not match the invariant

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#2]
https://github.com/Enfilde/CallsAndContacts/blob/5ca4aee6f193e8c2c37c19990d38b535cce4c6ff/src/main/Main/Call.java#L17
Result of called default constructor has null-reference of each field.

**Comment by Enfilde** [comment]
This constructor is used to access fields without initializing fields; it is used in the 160-170 line of the controller class
