### ISSUE TITLE
Don't define constructors invariant outside

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#3]
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L14-L18
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L21-L23
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L28
Calls' constructor invariant checked outside of it. Do it exactly in class constructor.

**Comment by Enfilde** [comment]
Fixed
