### ISSUE TITLE
Extra variable

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#6]
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L59-L65
Created variable used only once. Full name can be returned exactly from "if". Phone number is unique according to Controller.addCall.

**Comment by Alexander-Degtyar** [comment]
Can be refactored just like:
```
public String getContactName(int callIndex) throws CallsException { 
     return callsList.get(callIndex).fullName; 
 }
```

**Comment by Enfilde** [comment]
Сan't be so.

**Comment by Alexander-Degtyar** [comment]
Empty string still not required. Null reference at the beginning would be enough.
