### ISSUE TITLE
Extra variables

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/CallsAndContacts#9]
https://github.com/Enfilde/CallsAndContacts/blob/c9c908e3c80f34b6e4eaa674108a3b028de121f5/src/main/Main/Controller.java#L128-L129
Use one reference to Call instead of two references to (maybe) fields.

**Comment by Enfilde** [comment]
Fixed

**Comment by Alexander-Degtyar** [comment]
Not fixed. Empty strings still created.
